# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f41195c0e9cf166371b60abd87558c05"
name = "admin-action-app"
handle = "admin-action-app-6"
application_url = "https://heard-fact-accidents-istanbul.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_app_proxy,write_products"

[auth]  
redirect_urls = [
  "https://heard-fact-accidents-istanbul.trycloudflare.com/auth/callback",
  "https://heard-fact-accidents-istanbul.trycloudflare.com/auth/shopify/callback",
  "https://heard-fact-accidents-istanbul.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://button-sells-uploaded-brandon.trycloudflare.com/app/proxy"
subpath = "reviews"
prefix = "apps"

[pos]
embedded = false
